--- #YAML:1.0
name:               SSH-Command
version:            0.0.1
abstract:           SSH::Command - interface to execute multiple commands on host by SSH protocol
author:
    - NRG <pavel.odintsov@googlemail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              0
    Data::Dumper:      0
    File::Temp:        0
    Getopt::Long:      0
    Net::SSH2:         0
    Scope::Guard:      0
    Test::LongString:  0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
